services:
  todoapp-backend:
    image: todoapp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    container_name: todoapp-backend-container