# Use the official .NET SDK image for development
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet build -c Debug --no-restore

# Set the entry point to dotnet watch
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]