services:
  todoapp-backend:
    image: todoapp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestDatabase;User=sa;Password=${DB_PASSWORD};
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - dev-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}  #Should match the 'sa' password for now in .env file
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge