services:
  todoapp-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"  # Map host port 80 to container port 80
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestDatabase;User=sa;Password=${DB_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - prod-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD} #Should match the 'sa' password for now in .env file
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge