services:
  todoapp-backend:
    container_name: ToDoApp-Backend
    build:
      context: .
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile if needed
    ports:
      - "${APP_PORT:-5000}:8080"  # Map port 8080 in the container to APP_PORT on the host
      - "${SSL_PORT:-5001}:8081"  # Map port 8081 in the container to SSL_PORT on the host
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestDatabase;User=sa;Password=${DB_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - API_SERVER=${API_SERVER}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge