services:
  todoapp-backend:
    container_name: ToDoApp-Backend
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "${APP_PORT:-5000}:8080" # Default to 5000 for development, can override with environment variable
      - "${SSL_PORT:-5001}:443"  # Default to 5001 for development, can override with environment variable
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestDatabase;User=sa;Password=${DB_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network
    profiles:
      - dev
      - prod

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    profiles:
      - dev
      - prod

networks:
  app-network:
    driver: bridge