// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoAppBackend.Models;

#nullable disable

namespace ToDoAppBackend.Migrations
{
    [DbContext(typeof(TaskItemContext))]
    [Migration("20240915212622_UpdateTaskItemNullableFields")]
    partial class UpdateTaskItemNullableFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoAppBackend.Models.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("ParentTaskId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaskDataState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TaskItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TaskItemMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("TaskItemMessageId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("ToDoAppBackend.Models.TaskItemMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<long[]>("ReferencedTaskIds")
                        .HasColumnType("bigint[]");

                    b.HasKey("Id");

                    b.ToTable("TaskItemMessage");
                });

            modelBuilder.Entity("ToDoAppBackend.Models.TaskItem", b =>
                {
                    b.HasOne("ToDoAppBackend.Models.TaskItem", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("TaskItemId");

                    b.HasOne("ToDoAppBackend.Models.TaskItemMessage", "TaskItemMessage")
                        .WithMany()
                        .HasForeignKey("TaskItemMessageId");

                    b.Navigation("TaskItemMessage");
                });

            modelBuilder.Entity("ToDoAppBackend.Models.TaskItem", b =>
                {
                    b.Navigation("SubTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
